[package]
name = "Cryptonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

concrete = { version = "0.2.0-beta.2", features = [ "booleans", "shortints", "integers", "serde"] }
bincode = "1.3.3"